from __future__ import annotations


STORY_STEPS = [
    {
        "id": "warming_overview",
        "slug": "Warming",
        "title": "A Planet That Is Warming",
        "variable": "t2m",
        "region": "Global",
        "visual_component": "heatmap_layer",
        "year_range": ("1900-01-01", "2023-12-01"),
        "narrative_text": "Global temperatures have increased dramatically over the past century, and the warming signal now appears in nearly every basin and continent.",
        "ai_insight": "Recent decades contain the warmest years in the instrument record, with the strongest persistent anomalies appearing after 1990.",
    },
    {
        "id": "regional_patterns",
        "slug": "Arctic",
        "title": "Warming Is Not Equal Everywhere",
        "variable": "t2m",
        "region": "Arctic",
        "visual_component": "3d_globe",
        "year_range": ("2000-01-01", "2023-12-01"),
        "comparison_range": ("1951-01-01", "1970-12-01"),
        "narrative_text": "Certain regions such as the Arctic warm much faster than the global average, which changes sea ice, circulation, and downstream weather patterns.",
        "ai_insight": "This phenomenon is called Arctic amplification, and it is one of the clearest regional climate signatures in the demo dataset.",
    },
    {
        "id": "temperature_trend",
        "slug": "Trend",
        "title": "Climate Change Over Time",
        "variable": "t2m",
        "region": "Global",
        "visual_component": "line_chart",
        "year_range": ("1950-01-01", "2023-12-01"),
        "narrative_text": "Long-term temperature records reveal a clear upward trend rather than a short-lived fluctuation.",
        "ai_insight": "The persistent upward slope indicates a structural warming pattern rather than isolated single-year spikes.",
    },
    {
        "id": "extreme_events",
        "slug": "Events",
        "title": "More Frequent Extreme Events",
        "variable": "wind_speed",
        "region": "Global",
        "visual_component": "event_markers",
        "year_range": ("2010-01-01", "2023-12-01"),
        "narrative_text": "Extreme weather events are becoming more frequent and more operationally important for cities, infrastructure, and public health.",
        "ai_insight": "Warmer air and oceans increase the likelihood of severe heat, intense rainfall, and compound climate stress events.",
    },
    {
        "id": "future_projection",
        "slug": "Projection",
        "title": "Future Climate Scenarios",
        "variable": "t2m",
        "region": "Global",
        "visual_component": "projection_map",
        "year_range": ("2010-01-01", "2023-12-01"),
        "narrative_text": "Climate scenarios show that long-term warming can diverge sharply depending on how quickly emissions are reduced.",
        "ai_insight": "Lower-emissions pathways flatten the warming curve meaningfully, while delayed action compounds heat risk later in the century.",
        "scenarios": ["low_emissions", "medium_emissions", "high_emissions"],
    },
]
